# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-25 10:26
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Borough',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gss', models.CharField(blank=True, db_index=True, max_length=100)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('population', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RegisteredPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(blank=True)),
                ('postcode', models.CharField(blank=True, max_length=100)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('borough', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.Borough')),
            ],
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gss', models.CharField(blank=True, db_index=True, max_length=100)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('population', models.IntegerField(blank=True, null=True)),
                ('borough', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.Borough')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='registeredperson',
            name='ward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.Ward'),
        ),
    ]
