# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-25 13:57
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_registeredperson_postcode_error'),
    ]

    operations = [
        migrations.AddField(
            model_name='borough',
            name='area',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, geography=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='ward',
            name='area',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, geography=True, null=True, srid=4326),
        ),
    ]
