# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 10:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0007_auto_20160526_0900'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostcodeCacheData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postcode', models.CharField(blank=True, max_length=100)),
                ('borough', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='register.Borough')),
                ('ward', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='register.Ward')),
            ],
        ),
    ]
