# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 12:41
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0010_registeredperson_borough_gss'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcodecachedata',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
