# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0011_postcodecachedata_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='borough',
            name='percent_registered',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ward',
            name='percent_registered',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
