# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-27 08:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0012_auto_20160526_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='borough',
            name='registered_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ward',
            name='registered_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
