# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-28 06:28
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0013_auto_20160527_0850'),
    ]

    operations = [
        migrations.CreateModel(
            name='LLSOA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gss', models.CharField(blank=True, db_index=True, max_length=100)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('population', models.IntegerField(blank=True, null=True)),
                ('population_young', models.IntegerField(blank=True, null=True)),
                ('population_voting_age', models.IntegerField(blank=True, null=True)),
                ('percent_registered', models.IntegerField(blank=True, null=True)),
                ('registered_count', models.IntegerField(blank=True, null=True)),
                ('area', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, geography=True, null=True, srid=4326)),
                ('ward', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='register.Ward')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
