# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-29 05:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0015_auto_20160529_0556'),
    ]

    operations = [
        migrations.AddField(
            model_name='borough',
            name='growth_rate',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='llsoa',
            name='growth_rate',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='ward',
            name='growth_rate',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=4, null=True),
        ),
    ]
