# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-29 06:50
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0016_auto_20160529_0559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borough',
            name='area',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='llsoa',
            name='area',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='ward',
            name='area',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326),
        ),
    ]
