# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-29 07:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0017_auto_20160529_0650'),
    ]

    operations = [
        migrations.AddField(
            model_name='borough',
            name='max_year',
            field=models.IntegerField(blank=True, default=2014, null=True),
        ),
        migrations.AddField(
            model_name='llsoa',
            name='max_year',
            field=models.IntegerField(blank=True, default=2014, null=True),
        ),
        migrations.AddField(
            model_name='ward',
            name='max_year',
            field=models.IntegerField(blank=True, default=2014, null=True),
        ),
    ]
