# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 05:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0018_auto_20160529_0755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borough',
            name='growth_rate',
        ),
        migrations.RemoveField(
            model_name='borough',
            name='max_year',
        ),
        migrations.RemoveField(
            model_name='borough',
            name='population_2014',
        ),
        migrations.RemoveField(
            model_name='borough',
            name='population_voting_age_2014',
        ),
        migrations.RemoveField(
            model_name='borough',
            name='population_young_2014',
        ),
        migrations.RemoveField(
            model_name='llsoa',
            name='growth_rate',
        ),
        migrations.RemoveField(
            model_name='llsoa',
            name='max_year',
        ),
        migrations.RemoveField(
            model_name='llsoa',
            name='population_2014',
        ),
        migrations.RemoveField(
            model_name='llsoa',
            name='population_voting_age_2014',
        ),
        migrations.RemoveField(
            model_name='llsoa',
            name='population_young_2014',
        ),
        migrations.RemoveField(
            model_name='ward',
            name='growth_rate',
        ),
        migrations.RemoveField(
            model_name='ward',
            name='max_year',
        ),
        migrations.RemoveField(
            model_name='ward',
            name='population_2014',
        ),
        migrations.RemoveField(
            model_name='ward',
            name='population_voting_age_2014',
        ),
        migrations.RemoveField(
            model_name='ward',
            name='population_young_2014',
        ),
        migrations.AlterField(
            model_name='borough',
            name='gss',
            field=models.CharField(blank=True, db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='llsoa',
            name='gss',
            field=models.CharField(blank=True, db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='ward',
            name='gss',
            field=models.CharField(blank=True, db_index=True, max_length=100, unique=True),
        ),
    ]
