# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 05:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0019_auto_20160530_0526'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postcodecachedata',
            name='borough',
        ),
        migrations.RemoveField(
            model_name='postcodecachedata',
            name='ward',
        ),
        migrations.AddField(
            model_name='postcodecachedata',
            name='borough_gss',
            field=models.CharField(db_index=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='postcodecachedata',
            name='ward_gss',
            field=models.CharField(db_index=True, max_length=30, null=True),
        ),
    ]
