# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 18:32
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeographImage',
            fields=[
                ('image_id', models.IntegerField(primary_key=True, serialize=False)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('SON_AVG', models.FloatField()),
            ],
        ),
    ]
