# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 20:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share_images', '0002_geographimage_orig_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='geographimage',
            name='dream_image',
            field=models.ImageField(max_length=800, null=True, upload_to='images/dreams/'),
        ),
    ]
