# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 21:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0021_auto_20160530_0608'),
        ('share_images', '0003_geographimage_dream_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareImage',
            fields=[
                ('ward', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='register.Ward')),
                ('image', models.ImageField(max_length=800, null=True, upload_to='images/shares/')),
            ],
        ),
    ]
